sudo: required

services:
  - docker

before_install:
  - docker build -t montecb/react-test -f ./client/Dockerfile.dev ./client

scripts:
  - docker run -e CI=true montecb/react-test npm test

after_success:
  - docker build -t montecb/fib-client ./client
  - docker build -t montecb/fib-nginx ./nginx
  - docker build -t montecb/fib-server ./server
  - docker build -t montecb/fib-worker ./worker
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  - docker push montecb/fib-client
  - docker push montecb/fib-nginx
  - docker push montecb/fib-server
  - docker push montecb/fib-worker


deploy:
  provider: elasticbeanstalk
  region: 'us-east-2'
  app: 'multi-docker'
  env: 'MultiDocker-env'
  bucket_name: 'elasticbeanstalk-us-east-2-983336554509'
  bucket_path: 'docker-multi'
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY
