version: '3'
services:
  api:
    image: "montecb/fib-server"
    mem_limit: 128m
    hostname: api
    environment:
      - REDIS_HOST=$REDIS_HOST
      - REDIS_PORT=$REDIS_PORT
      - PGUSER=$PGUSER
      - PGHOST=$PGHOST
      - PGDATABASE=$PGDATABASE
      - PGPASSWORD=$PGPASSWORD
      - PGPORT=$PGPORT
  client:
    image: montecb/fib-client
    mem_limit: 128m
    hostname: client
  nginx:
    image: "montecb/fib-nginx"
    mem_limit: 128m
    hostname: nginx
    ports:
      - "80:80"
  worker:
    image: "montecb/fib-worker"
    mem_limit: 128m
    hostname: worker
    environment:
      - REDIS_HOST=$REDIS_HOST
      - REDIS_PORT=$REDIS_PORT
  